312

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -170,9 +170,16 @@ runs:
         LINT_MESSAGES=$(cd $FAP_SRC_PATH && ufbt lint 2>&1 | tee /dev/fd/2)
         # Capture error code
         LINT_STATUS=$?
-        # Save multiline output
-        echo "lint-messages<<EOF" >> $GITHUB_OUTPUT
-        echo "$LINT_MESSAGES" >> $GITHUB_OUTPUT
-        echo "EOF" >> $GITHUB_OUTPUT        
-        # Exit with error code
-        exit $LINT_STATUS
+        if [ $LINT_STATUS -eq 0 ]; then
+          echo "Lint passed" >> $GITHUB_STEP_SUMMARY
+        else 
+          # Save multiline output
+          echo "lint-messages<<EOF" >> $GITHUB_OUTPUT
+          echo "$LINT_MESSAGES" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
+          echo "Lint errors:\n\`\`\`\n" >> $GITHUB_STEP_SUMMARY
+          echo $LINT_MESSAGES >> $GITHUB_STEP_SUMMARY
+          echo "\n\`\`\`\n" >> $GITHUB_STEP_SUMMARY
+          # Exit with error code
+          exit $LINT_STATUS
+        fi
