aaa

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -48,17 +48,18 @@ inputs:
     default: ${{ false }}
 
 outputs:
+  fap-artifacts:
+    description: "Application build artifacts"
+    value: ${{ steps.build-fap.outputs.build_artifacts }}
+
+  ufbt-status:
+    description: JSON status object for ufbt
+    value: ${{ steps.ufbt-status.outputs.json }}
+
   toolchain-version:
     description: Toolchain version
     value: ${{ steps.get-tooclhain-version.outputs.required-version }}
 
-  ufbt-status:
-    description: Status object for ufbt
-    value: ${{ steps.ufbt-status.outputs.status }}
-
-  fap-artifacts:
-    description: "Application build artifacts"
-    value: ${{ steps.build-fap.outputs.build_artifacts }}
 
 runs:
   using: composite
@@ -107,29 +108,25 @@ runs:
         ufbt update $UFBT_UPDATE_ARGS
 
     - name: Get ufbt status as JSON
-      id: get-ufbt-status
-      shell: bash
-      run: |
-        echo "raw=$(ufbt status --json)" >> $GITHUB_OUTPUT
-
-    - name: Parse ufbt status
       id: ufbt-status
       shell: bash
       run: |
-        echo "status=${{ fromJSON(steps.get-ufbt-status.outputs.raw) }}" >> $GITHUB_OUTPUT
-        
+        echo "json=$(ufbt status --json)" >> $GITHUB_OUTPUT
+
+
     - name: Check toolchain version
       id: get-tooclhain-version
       shell: bash
       run: |
-        echo "required-version=`bash -c "export $(grep FBT_TOOLCHAIN_VERSION\= ${{ steps.ufbt-status.outputs.status.sdk_dir }}/scripts/toolchain/fbtenv.sh) printenv FBT_TOOLCHAIN_VERSION"`" >> $GITHUB_OUTPUT
-        echo "deployed-version=`cat ${{ steps.ufbt-status.outputs.status.toolchain_dir }}/*/VERSION 2>/dev/null || echo 0`" >> $GITHUB_OUTPUT
+        # echo "toolchain-dir=${{ parseJSON(steps.ufbt-status.outputs.json).toolchain_dir }}" >> $GITHUB_OUTPUT
+        echo "required-version=`bash -c "export $(grep FBT_TOOLCHAIN_VERSION\= ${{ parseJSON(steps.ufbt-status.outputs.json).sdk_dir }}/scripts/toolchain/fbtenv.sh) printenv FBT_TOOLCHAIN_VERSION"`" >> $GITHUB_OUTPUT
+        echo "deployed-version=`cat ${{ parseJSON(steps.ufbt-status.outputs.json).toolchain_dir }}/*/VERSION 2>/dev/null || echo 0`" >> $GITHUB_OUTPUT
         
     - name: Cache toolchain
       uses: actions/cache@v3
       if: steps.get-tooclhain-version.outputs.required-version != steps.get-tooclhain-version.outputs.deployed-version
       with:
-        path: ${{ steps.ufbt-status.outputs.status.toolchain_dir }}
+        path: ${{ parseJSON(steps.ufbt-status.outputs.json).toolchain_dir }}
         key: ${{ runner.os }}-fbt-toolchain-${{ steps.ufbt-status.outputs.toolchain_version }}
 
     - name: Set fap source path
@@ -153,8 +150,3 @@ runs:
         DIST_PATH=`pwd`/dist
         echo "build_artifacts=$(ls $DIST_PATH/*.fap)" >> $GITHUB_OUTPUT
 
-    - name: Upload app artifacts
-      uses: actions/upload-artifact@v3
-      with:
-        name: app-artifacts
-        path: ${{ steps.build-fap.outputs.build_artifacts }}
